### ISSUE TITLE
The getter 'iterator' was called on null.

### ISSUE THREAD

**Issue by prabhunath111** [rajayogan/flutter-googlemaps-routes#1]
[ERROR:flutter/lib/ui/ui_dart_state.cc(148)] Unhandled Exception: NoSuchMethodError: The getter 'iterator' was called on null.
E/flutter ( 6192): Receiver: null
E/flutter ( 6192): Tried calling: iterator

**Comment by rajayogan** [comment]
Add billing to google account and use directions api
