### ISSUE TITLE
"the iterator was called on null" issue

### ISSUE THREAD

**Issue by dw-Kwon** [rajayogan/flutter-googlemaps-routes#2]
environment : 
Flutter version : v1.12.13+hotfix.8
google_maps_flutter: ^0.5.24+1
google_map_polyline: 0.2.0+1

I did run your code but until just draw polyline from origin to destination Latitude, Longitude.
But I got "the iterator was called on null"

I guess It was not finish get RouteCoords code but invoked onMapCreated method so try to make polyline list with not finished routeCoords data. 

so I revised some position of code.
in getSomePoints method

      List<LatLng> points = await googleMapPolyline.getCoordinatesWithLocation(
            origin: LatLng(40.6782, -73.9442),
            destination: LatLng(40.6944, -73.9212),
            mode: RouteMode.driving);

      setState(() {
        routeCoords = points;
        // change position from onMapCreated(GoogleMapController controller) method
        polyline.add(
            Polyline(
              polylineId: PolylineId('route1'),
              visible: true,
              points: routeCoords,
              width: 4,
              color: Colors.blue,
              startCap: Cap.roundCap,
              endCap: Cap.buttCap,
            )
        );
      });

This is work for me.

**Comment by rajayogan** [comment]
Thank you.
